# Generated by Django 5.1.3 on 2024-11-18 18:17

import django.db.models.deletion
import meteora.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('make_in', models.DateField()),
                ('update_in', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_stock', models.DecimalField(decimal_places=0, max_digits=1000)),
                ('image', models.ImageField(upload_to='')),
                ('make_in', models.DateField(auto_now_add=True)),
                ('update_in', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteora.category')),
            ],
        ),
    ]
