# Generated by Django 5.1.3 on 2024-11-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteora', '0003_alter_category_make_in_alter_category_update_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='descricao',
            new_name='description',
        ),
    ]
