# Generated by Django 5.1.3 on 2024-11-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteora', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
